### ISSUE TITLE
opt/openwrt文件夹内容直接读取F大的库是不是比较好......

### ISSUE THREAD

**Issue by doctor-design** [mingxiaoyu/flippy-packages#1]
如题
这部分就可以免维护而保持同步了

**Comment by mingxiaoyu** [comment]
想过这个问题。就怕F大 一个不小心更新出一个bug 。当时没修复。这个actions 就裂了

**Comment by mingxiaoyu** [comment]
我计划写一个action来同步F大脚步。就是内核。这个比较烦。我上班时候。周末白天都没办法第一时间更新

**Comment by mingxiaoyu** [comment]
@doctor-design  谢谢你的意见

**Comment by mingxiaoyu** [comment]
@doctor-design  出两个版本？
v1和main 读取这里的
f 读取F大？爆了找F大系列？

**Comment by doctor-design** [comment]
你的编译既然都是基于F大的...所以这里只需要最大限度地及时同步F大的数据就好（使这里人工干预程度最小化），假如那里出现BUG爆了（其实这只是基于上述思路完成基础上才该考虑的），那也是上游水污染了，第二步在考虑补救...呵呵，我不会编程纯属“想当然”。

**Comment by mingxiaoyu** [comment]
@doctor-design 
现在这么做还在考虑。
不过你提到的，在通用一些？
我想知道，你现在感觉那里还不够好？大家一起探讨一下 :)



>

**Comment by doctor-design** [comment]
像我们这种小白的需求最理想的状态当然是“走进去的是猪，出来时是罐头”了.......
我们不用考虑你后面怎么编译怎么拿大佬的内核等步骤....上来只需填一张“表”
里边存放诸如：“机型”“config文件名”“Releases的注释”“Releases保存天数”....等等包括你现在已经已存在的传递的变量（脚本这样做起来就会很麻烦增加很多变量），这样我们就完全不用打开你的脚本再去改里面的参数，最好config文件名也可以自定义，为防止循环太多可以限制一种机型最多可编译版本数（比如现在的两个）。所以这样看来工作量主要还是在前边的编译脚本环节上面。
这就达到傻瓜型编译了。当然使用者必须能够自己完成config和diy-part2的制作(像我一般是复制粘贴别人)....
以上
