### ISSUE TITLE
CPU 性能优化调节设置

### ISSUE THREAD

**Issue by roacn** [mingxiaoyu/flippy-packages#2]
想让N1的CPU跑的频率更宽一些，不太用的时候可以自动降频、夏天也能待机温度低些，现在是维持在1000MHz以上。
F大编译版本里的“系统”→“CPU 性能优化调节设置”，这个补丁能调出来吗？
是cpufreq这个吗

**Comment by mingxiaoyu** [comment]
CONFIG_PACKAGE_luci-app-cpufreq=y
好像是这个
