### ISSUE TITLE
一点看法

### ISSUE THREAD

**Issue by doctor-design** [mingxiaoyu/flippy-packages#5]
。。关闭

**Comment by mingxiaoyu** [comment]
简单的说下吧。我之所以要改为nodejs版本有两个原因

1. 工作用的电脑是window 10.要调试 shell 脚本要用我个人流量连接我的VPS ，然后在调试。这个对我来说很麻烦
2. 我刚好想试下我nodejs的UT（集成测试）。

对于想显示是谁打包的，可以这样

    - name: Package OpenWrt with flippy script      
       uses: mingxiaoyu/package-flippy-openwrt@main     
         with:       
           types: s905d          
           whoami: <你的名字>
           penwrt-path: openwrt/bin/targets/*/*



现在这个版本对大部分人来说。基本可以开箱即食。openwrt-path 。本来可以设置默认值：openwrt/bin/targets/*/*
想想还是让用户自己填。

1. 不然仅仅是打包，不编译的用户，会说。为什么我没有打包成功。。。。
2. 我之前的项目是仅仅打包，也是历史遗留问题吧。
